### ISSUE TITLE
302 Redirect

### ISSUE THREAD

**Issue by sarxan26** [codemix/yii2-localeurls#124]
Hi!
Thank you for this useful extension, but I noticed strange behavior. App's default language is english. Here is my config:

`    

            "enableLanguageDetection" => true,

            'enableDefaultLanguageUrlCode' => false,

            'languages' => ['en', 'ru', 'az'],

            'class' => 'codemix\localeurls\UrlManager',
`

Everything works just fine, except default language. What I mean is that, when the user enters the site for the first time, this  url ` https://example.com` returns 200 status code. Then he changes language to another. Again, no problems. Then he changes back to english and opens some page, for example ` https://example.com/page/restaurants-overview`. And here, if we inspect this page with browser dev tools, in networks section we'll see two requests:
` https://example.com/en/page/restaurants-overview` with status code - 302
and 
` https://example.com/page/restaurants-overview` with status code - 200.
I want to know, is there anyway to get rid of first request or this is normal behavior. 
Thanks!

**Comment by mikehaertl** [comment]
This is the expected behavior. You've set `enableDefaultLanguageUrlCode` to `false`. So the default language should not use a `/en` in the URL but a URL without any language code. That's exactly what happens.

Also read this, why this is neccessary: https://github.com/codemix/yii2-localeurls#reset-to-default-language
