### ISSUE TITLE
Something is very wrong

### ISSUE THREAD

**Issue by nurbeknurjanov** [codemix/yii2-localeurls#144]
Open chrome incognito
Go here:
https://sakuracommerce.com it works
Then go here
https://sakuracommerce.com/ru it works too
The go back here
https://sakuracommerce.com it doesnt work

I have only 2 language, en-US and ru (russian)

This is my config

        'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'enablePrettyUrl'=>true,
            'showScriptName'=>false,
            'enableLanguageDetection'=>false,
            'languages' => ['en-US', 'ru'],
        ],

Please help.

**Comment by nurbeknurjanov** [comment]
Mike, I mean site is not opening.
Please look here
https://www.dropbox.com/s/e7sgbcxp0uqt4my/Screenshot%20from%202018-08-04%2013-40-28.png?dl=0

And here

https://www.dropbox.com/s/pi7ek24wz08uziu/Screenshot%20from%202018-08-04%2013-40-39.png?dl=0

I think, it says something to you, I do not do anything. Everything is standard

**Comment by mikehaertl** [comment]
As you have nothing special in your configuration and our extension here is proven to work just fine in these cases I have to assume that something else is misconfigured on your side.

I'm sorry, but I can't help you with that as we don't provide any support. You have to debug the issue on your own. If you still think, that there's something broken that we have to fix, you can report back here. But please provide more details where you thinks something must be fixed in our code.

**Comment by nurbeknurjanov** [comment]
On my local everything is ok. My local is apache.

On server here is nginx. Only on server here is this weird behavior

**Comment by mikehaertl** [comment]
Your screenshot doesn't help me much as there's no helpful error message.

All this extension does on HTTP level is basically create a redirect response when necessary. This can not break your app completely - unless there's an endless redirect. You should debug this and investigate what exactly is going on. If you can, you could use `curl` (e.g.  `curl -I https://...`) to inspect the response headers and if they contain a redirect.

Also check the yii log for the past couple requests and look at the trace messages from our extension to find out what's going on inside.

As said before, so far this is not a clear bug to me.
