### ISSUE TITLE
Problem with default language

### ISSUE THREAD

**Issue by DesRodman** [codemix/yii2-localeurls#149]
Good day
I found a problem in browser Google Chrome
Default language is ENGLISH, at first time browser is opening site on russian language.
I can just between other languages, but if i want to open in english - site goes to russian (default language of browser)

At same time under Firefox - language switching works fine

What i did wrong?

Thanks

**Comment by mikehaertl** [comment]
Sorry, with the information you give, I can't help you.  The extension is well tested and widely in use, so I can say with some certainty that whatever your problem is, it's probably some misconfiguration - or expected behavior.

Maybe check the README again very thoroughly. Your problem also sounds somewhat like this:
https://github.com/codemix/yii2-localeurls#reset-to-default-language

I'm closing this for now unless you can provide a configuration example and a clear description what to do to reproduce the issue.

**Comment by DesRodman** [comment]
here my common config
`
 'sourceLanguage' => 'en',
    'language' => 'en',
....
 'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'languages' => ['en', 'ru', 'zh', 'hi', 'de'],
            'enableDefaultLanguageUrlCode' => false,
            'enableLanguagePersistence' => false,
            'rules' => [
                //
            ],
        ],`

menu i'm creating via 
`$buttons .= '<li>'.Html::a( $lang->name, Url::to(['/' . $lang->url, 'language' => $lang->url])).'</li>';`

all like in README
but why problem - cant understand

**Comment by mikehaertl** [comment]
I can not really help. Check the code, it's not that complex. Try to debug and find out what's wrong.
