### ISSUE TITLE
Switch to a user configured language during login

### ISSUE THREAD

**Issue by rolblo12** [codemix/yii2-localeurls#15]
I wonder if there is a way to switch to a language that logged-in users have configured for themselves.
So the language would come from a user record (not part of this extension of course). 
During the logged in state the language persistence of this extension would not be used.

I thought to set `Yii::$app->language` explicitely during the controller `init()` method, if the user is no guest. However a few days ago it did not work like that.

**Comment by mikehaertl** [comment]
That's out of the scope of this extension. You can easily do so by configuring your own `User` class, where you implement an [afterLogin()](http://www.yiiframework.com/doc-2.0/yii-web-user.html#afterLogin()-detail) method. There you can check the user language from DB. In order to persist it with the localeurls extension you can then do a redirect to an URL that contains this user language.
