### ISSUE TITLE
Impossible to use language parameter to tranlsate urls?

### ISSUE THREAD

**Issue by ettolo** [codemix/yii2-localeurls#52]
Hi,
your extension works well for me unless i need to translate urls for seo purposes.
For example:
'http://mysite.com/en/user' should become 'http://mysite.com/it/utente';

i could wite these rules in urlManager:
<language:it>/utente => /user/index
<language:en>/user=> /user/index

but this won't work because the language parameter is stripped from the url before the rules are applied.
Am i missing something?
Thank you!

**Comment by mikehaertl** [comment]
If you use this extension, you can't use URL rules that also use the language parameter. That's by design. In your case you'd probably want to use a custom UrlRule class and deal with language specific URLs there. The language is already set in `Yii::$app->language` at that point. http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#creating-rules

**Comment by ettolo** [comment]
Thank you!
