### ISSUE TITLE
language appended to the end of the url?

### ISSUE THREAD

**Issue by marko85to** [codemix/yii2-localeurls#68]
Hi and thanks for your extension!

I have followed the instructions but it seems the language is appended to the end of the URLs instead of before the script name:
**http://localhost/yii/advanced/frontend/web/index.php/en**

Also, I have tried to disable the option "showScriptName" and the URL:
**http://localhost/yii/advanced/frontend/web/en**
is not found -> 404 not found.

Am I doing something wrong?

Thank you

**Comment by mikehaertl** [comment]
Both is expected behavior.

Your webserver's document root does not point to the directory of `index.php`. So all your URLs will always require the static `yii/advanced/frontend/web` prefix, because that's the base URL of your application. We can't modify this or the webserver would not find the Yii app's `index.php` anymore (unless you use mod rewrite or similar - which is beyound the scope of this extension).

The language code can only be added to the application specific part of the URL. So maybe you should try to change the document root of your webserver to point to the `web` directory.

**Comment by marko85to** [comment]
Thanks for the reply. I have just added a vhost and now http://mysite points to the yii/advanced/frontend/web directory. I have exact the same problem:
**http://mysite** redirects to **http://mysite/en** which returns a white page "Not found".
It has to be an error in some configuration or I am missing something.

Am I supposed to create any URL rule or create a controller/view with the name of the language or everything should already work with my index.php?

Thank you!

**Comment by mikehaertl** [comment]
You've probably still `showScriptName` set to `false` and are missing the rewrite part in your webserver configuration:

http://www.yiiframework.com/doc-2.0/guide-start-installation.html#configuring-web-servers

**Comment by marko85to** [comment]
Amazing! I have solved it! Thank you so much!! 💯  :)
