### ISSUE TITLE
Error on documentation about excluding routes url

### ISSUE THREAD

**Issue by nacesprin** [codemix/yii2-localeurls#86]
https://github.com/codemix/yii2-localeurls#excluding-routes--urls

If I use this example configuration:

```
<?php
    'ignoreLanguageUrlPatterns' => [
        '#^site/(login|register)#' => '#^(login|register)#',
        '#^api/#' => '#^api/#',
    ],
```

It generates redirection loop when accessing to /site/login

I've had to change it to: ('site' added)
```
<?php
    'ignoreLanguageUrlPatterns' => [
        '#^site/(login|register)#' => '#^site/(login|register)#',
        '#^api/#' => '#^api/#',
    ],
```

So, with that configuration the redirections loop are solved.

**Comment by mikehaertl** [comment]
The example assumes, that you have a URL rule for `/login` pointing to `site/login`. It's really to demonstrate that there's a difference between keys and values.

**Comment by nacesprin** [comment]
I had a headache due to that issue. Possibly more users had it too. Is not there any way to warn about the possible redirect loop?

**Comment by mikehaertl** [comment]
Hmm, in my view, a developer should not simply copy & paste the example but fully understand each part. I've modified the example so that it's clearer that the left hand side is a URL pattern, that can differ completely from the correlated route. I don't want to go into detail about url configuration. This is already covered in the Yii 2 guide.
