### ISSUE TITLE
HTTP status code for redirectToLanguage

### ISSUE THREAD

**Issue by dudesquare** [codemix/yii2-localeurls#95]
Thanks for this very useful extension. I would just like to know if you could add the option to add the HTTP status code for the redirect in the method redirectToLanguage (line 468).

**Comment by mikehaertl** [comment]
Hmm, why would you want to change that? I don't think that anything else but the default 302 makes sense.

**Comment by dudesquare** [comment]
Thanks for your fast reply. It's a request from my client, he says it's better for SEO to redirect with a 301 since it's a permanent redirect.

**Comment by mikehaertl** [comment]
I'm not really sure, if this is a good idea. The extension performs redirects in different situations. While some of them may use a 301 it's for sure not true for all of them. For example if language detection is enabled (default) then different users could see different redirect target URLs for the same original URL. If we send a permanent redirect in this case, a search engine may index the redirect URL instead of the original URL. And it could show this specific language URL in it's search result - which basically disables autodection for any visitor that follows the search result link.

Maybe you can show a concrete example how you configured the extension and for which redirect you think a 301 makes sense. Then we can discuss further and see if we find a viable solution.

**Comment by dudesquare** [comment]
You have a very good point there. I guess I would like to be able to redirect the default language URL code to the root domain with a 301 ($enableDefaultLanguageUrlCode = false: e.g. http://domain.com/en/ => http://domain.com/), and use 302 for redirects caused by language detection. Does that make sense?

**Comment by dudesquare** [comment]
I just noticed I have a misconfiguration where my default language is 'en-GB' and my current language is 'en'. So unless my site has been indexed with a different configuration (e.g. change $enableDefaultLanguageUrlCode true to false) my current problem should not occur.

**Comment by mikehaertl** [comment]
Ok, so I'm closing this for now unless you think it's still something we need to fix.
