### ISSUE TITLE
enableDefaultLanguageUrlCode coflicts with yii\web\UrlNormalizer

### ISSUE THREAD

**Issue by Matvik** [codemix/yii2-localeurls#97]
When setting enableDefaultLanguageUrlCode = true and having UrlNormalizer enabled, we has wrong redirect, when UrlNormalizer works, example: 

> /uk/about-us

redirects to 
> /uk/uk/about-us/

UrlManager config:
```
'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => ['uk' => 'uk-UA', 'ru' => 'ru-RU'],
            'enableDefaultLanguageUrlCode' => true,
            'enablePrettyUrl' => true,
            'baseUrl' => '/',
            'showScriptName' => false,
            'suffix' => '/',
            'normalizer' => [
                'class' => 'yii\web\UrlNormalizer',
                'action' => yii\web\UrlNormalizer::ACTION_REDIRECT_PERMANENT,
            ],
            'rules' => require(__DIR__ . '/router.php')
        ],
```

**Comment by mikehaertl** [comment]
@Matvik These UrlNormalizer issues start to get ugly. I've tried to fix this and according to our tests it seems to work. The problem is, that I now don't really know, why it works :stuck_out_tongue_winking_eye:. This will for sure haunt me forever.

Could you please help test this with the latest `UrlManager.php` you find on the master branch?

**Comment by Matvik** [comment]
Yes, now it works fine! Thank you.

**Comment by mikehaertl** [comment]
@Matvik Have you seen my comment in #94? Is this the same problem as you mentioned in your comment here: https://github.com/codemix/yii2-localeurls/issues/94#issuecomment-288428815

**Comment by Matvik** [comment]
No, this fix did not help there.
