### ISSUE TITLE
ignoreLanguageUrlPatterns on AJAX request?

### ISSUE THREAD

**Issue by winternet-studio** [codemix/yii2-localeurls#98]
Would it be possible to have an option where you can make it ignore language whenever the request is an AJAX request (Yii::$app->request->isAjax == true)?

Most of my AJAX requests are to the api controller but I also have a few other controller/actions which are used both for AJAX and non-AJAX requests...

**Comment by mikehaertl** [comment]
I think if our extension interferes with your AJAX request, you're doing something wrong. You should create the AJAX URLs with correct language so that no redirect occurs.

Alternatively you can use the [ignoreLanguageUrlPattern](https://github.com/codemix/yii2-localeurls#excluding-routes--urls) e.g. to exclude your API controller from processing.

**Comment by winternet-studio** [comment]
I guess that's a valid opinion to have. Making the AJAX URLs include the language is more cumbersome because I have the URLs in clientside Javascript code and have to manually determine it for every call. But of course there are ways to work around it or simplify it.

Would also be nice to have an option for matching URLs from ignoreLanguageUrlPattern ignore the redirect as it currently does, but still load the default language from session/cookie for those URLs. But again, there are ways to work around that.
